services:
  - type: web
    name: insurance-lead-tracker
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # This means you'll need to manually enter the value in Render dashboard
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /health
    autoDeploy: true
