name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣  Check out the code
      - uses: actions/checkout@v4

      # 2️⃣  Install Node 18 (change if you use another version)
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # 3️⃣  Install dependencies
      - run: npm ci

      # 4️⃣  Build / test / (optional) lint
      - run: npm run build            # keep this
      # - run: npm test               # uncomment when you add tests
      # - run: npm run lint           # uncomment if you have a lint script

      # 5️⃣  Quick runtime smoke-test on a throw-away port
      - run: PORT=4000 npm run dev --if-present
